### ISSUE TITLE
onEnd callback

### ISSUE THREAD

**Issue by dlindenkreuz** [clari/react-tween#3]
The user should have a way to know when the animation has finished.

**Comment by mking-clari** [comment]
@dlindenkreuz great idea. added `onEnd`. let me know if you think there can be any improvement with it.

**Comment by dlindenkreuz** [comment]
Amazing, thanks for the quick implementation!

For `TransitionGroup`s, it might be useful to pass an ID (maybe the respective child element's `key`?) as callback parameter to figure out which element was removed or added.

**Comment by mking-clari** [comment]
Good idea. For now I'm going to stay within the lines given by react-tween, which has `onRest`, but doesn't go further. I want to keep the API difference minimal.
